name: Free Tier Auto Summary

on:
  schedule:
    - cron: '0 0 * * 1'   # 毎週月曜午前9時（JST）実行
  workflow_dispatch:       # 手動実行も可能

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai

      - name: Run summarizer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python script/summarize.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add summary.html
          git commit -m "Auto summary update (Free Tier)"
          git push